config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: "users/registrations" }

  get 'durian_runtuh', to: 'articles#most_views', as: :durian_runtuh
  get 'pedas', to: 'articles#trending', as: :pedas
  get 'latest', to: 'articles#latest', as: :latest
  get 'articles/search/:tag', to: 'articles#tag_search', as: :tag
  root 'articles#index'
  resources :articles do
  	resource :votes, only: [:upvote, :downvote] do
  		member do
  			get 'upvote'
        get 'downvote'
  		end
  	end
  end

  resources :devices, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :votes, dependent: :destroy
	is_impressionable
	acts_as_taggable_on :tags
	mount_uploaders :images, ImageUploader
	mount_uploaders :videos, VideoUploader

	# def set_success(format, opts)
  #   self.success = true
  # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :search]
  before_action :authenticate_user!, only: [:new, :create]
  impressionist :actions=>[:show,:index]

  def search
    if params[:search] == ""
      render :new
    else
      @article = Article.tagged_with(params[:search], :any => true,:wild => true)
      puts @article
    end
  end

  def tag_search
    if params[:tag] == ""
      render :new
    else
      @article = Article.tagged_with(params[:tag], :any => true,:wild => true)
      puts @article
    end
  end

  def latest
    @latest = Article.order('created_at desc')
  end

  def trending
    @all = Article.where("articles.created_at > ?", 7.day.ago)
    @articles = []
    @output =  []
    @all.each do |article|
      # change the minimum for views below
      if article.impressionist_count > 1
        p @articles << article
      end
    end
    @articles.each do |article|
      # Change the limit for vote count below
      if article.votes.count >= 1
        @output << article
      end
    end
  end

  def most_views
    @articles = []
    Article.all.each do |article|
      if article.impressionist_count > 1
        @articles << article
      end
    end
    @output = @articles.sort{ |a,b| a.impressionist_count <=> b.impressionist_count }
  end

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.left_joins(:votes).group(:id).order('COUNT(vote) DESC')
      @latest = Article.order('created_at DESC')
    end
    @client_ip = remote_ip()
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @articles = Article.left_joins(:votes).group(:id).order('COUNT(vote) DESC')
    tag_list = @article.tag_list
    relevant = Article.tagged_with(tag_list, :any => true,:wild => true)
    @relevant_tag = []

    relevant.each do |x|
      if x.id != @article.id
        @relevant_tag << x
      end
    end

    # impressionist(@article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create

    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.tag_list.add(params[:article][:tag_list], parse: true)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title , :description, {images: []}, {videos: []}, :user_id, tag_list: [])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def get_tags
    ActsAsTaggableOn::Tag.order(:name).map(&:name)
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |f| %>
<div class="form-row" style="padding: 0 15px;">
  <div class="form-group col-sm-4">
    <%= f.label :images, class: "col-form-label-sm"  %><br />
    <%= f.file_field :images, multiple: true , class: "form-control form-control-sm" %>
  </div>

  <div class="form-group col-sm-4">
    <%= f.label :videos, class: "col-form-label-sm"   %>
    <%= f.file_field :videos, multiple: true , class: "form-control form-control-sm" %>
  </div>
</div>
<div class="form-row" style="padding: 0 15px;">
  <div class="form-group col-sm-4">
    <%= f.label :title, class: "col-form-label-sm" %><br/>
    <%= f.text_field :title, class: "form-control form-control-sm" %>
  </div>

  <div class="form-group col-sm-4 ui-widget">
    <%= f.label :tag_list, "Insert Tags(Seperated by comma)", class: "col-form-label-sm"  %>
    <%= f.text_field :tag_list, id: "tag-search", class: "form-control form-control-sm autocomplete-tag", data: {autocomplete_source: ActsAsTaggableOn::Tag.order(:name).map(&:name)} %>
  </div>
  <datalist id="list"></datalist>
</div>
  <div class="form-group col-sm-6">
    <%= f.label :description, class: "col-form-label-sm"  %>
    <%= f.text_area :description, :class => "description-field", class: "form-control form-control-sm"  %>
  </div>
<div class="row">

  <div class="col">
    <%= link_to 'Back', articles_path , class: "rounded", style: "padding: 5px; margin: 5px;"%>
  </div>
  <div class="actions col-sm" >
    <%= f.submit "Submit", class: "rounded", style: "margin: 5px;" %>
  </div>
</div>
<% end %>

app/views/articles/edit.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120935558-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120935558-1');
</script>

<!-- Hotjar Tracking Code for http://uglymalaysia.vz2k7vdg9a.ap-southeast-1.elasticbeanstalk.com/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:948381,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/latest.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120935558-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120935558-1');
</script>

<!-- hotjar installed -->
<script>
  (function(h,o,t,j,a,r){
    h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
    h._hjSettings={hjid:948381,hjsv:6};
    a=o.getElementsByTagName('head')[0];
    r=o.createElement('script');r.async=1;
    r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
    a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<!-- hotjar end -->

<div class="container">
  <div class="header">
    <p class="title">Latest</p>
    <p class="subtitle">As fresh as they come!</p>
  </div>
  <% if @latest.empty? %>
  <div class="text-center">
    <p>Please come back later for more news!</p>
  </div>
  <% else %>
  <div class="row singles">
    <% @latest.each do |post|%>
    <div class="col-sm-12 col-md-4 col-lg-3 mb-3 px-2">
      <a href="articles/<%= post.id %>">
        <div class="card shadow-sm h-100">
          <div class="img-wrap">
            <% if post.images? %>
              <img class="card-img-top" src="<%= post.images[0].url%>" alt="Card image cap">
            <% else %>
              <img class="card-img-top" src="http://via.placeholder.com/325x325" alt="Card image cap">
            <% end %>
          </div>
          <div class="card-body d-flex flex-column">
            <div class="tags">
              <% post.tag_list.each do |tag| %>
                <button href="articles/search/<%= tag %>" class="btn btn-sm btn-outline-danger mb-1"><%= tag %></button>
              <%end%>
            </div>
            <p class="card-title"><%= post.title  %></p>
            <div class="stats d-flex flex-wrap justify-content-between mt-auto">
              <li><i class="fa fa-eye"></i> <%= post.impressionist_count(:filter=>:ip_address) %></p></li>
              <li><i class="fa fa-heart"></i> <%= Vote.where(article_id: post.id, vote: true).count %></li>
              <li><i class="fa fa-calendar"></i> <%= time_ago_in_words(post.created_at) unless post.created_at.blank? %> ago</li>
            </div>
          </div>
        </div>
      </a>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/articles/most_views.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120935558-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120935558-1');
</script>

<!-- hotjar installed -->
<script>
  (function(h,o,t,j,a,r){
    h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
    h._hjSettings={hjid:948381,hjsv:6};
    a=o.getElementsByTagName('head')[0];
    r=o.createElement('script');r.async=1;
    r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
    a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<!-- hotjar end -->

<div class="container">
  <div class="header">
    <p class="title">Durian Runtuh</p>
    <p class="subtitle">Stories where votes comes atumbling</p>
  </div>
  <% if @output.empty? %>
  <div class="text-center">
    <p>Please come back later for more news!</p>
  </div>
  <% else %>
  <div class="row singles">
    <% @output.each do |post|%>
    <div class="col-sm-12 col-md-4 col-lg-3 mb-3 px-2">
      <a href="articles/<%= post.id %>">
        <div class="card shadow-sm h-100">
          <div class="img-wrap">
            <% if post.images? %>
              <img class="card-img-top" src="<%= post.images[0].url%>" alt="Card image cap">
            <% end %>
          </div>
          <div class="card-body">
            <div class="tags">
              <% post.tag_list.each do |tag| %>
                <button href="articles/search/<%= tag %>" class="btn btn-sm btn-outline-danger"> <%= tag %> </button>
              <%end%>
            </div>
            <p class="card-title"><%= post.title  %></p>
            <div class="stats d-flex flex-wrap justify-content-between align-self-end">
              <li><i class="fa fa-eye"></i> <%= post.impressionist_count(:filter=>:ip_address) %></p></li>
              <li><i class="fa fa-heart"></i> <%= Vote.where(article_id: post.id, vote: true).count %></li>
              <li><i class="fa fa-calendar"></i> <%= time_ago_in_words(post.created_at) unless post.created_at.blank? %> ago</li>
            </div>
          </div>
        </div>
      </a>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120935558-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120935558-1');
</script>

<!-- Hotjar Tracking Code for http://uglymalaysia.vz2k7vdg9a.ap-southeast-1.elasticbeanstalk.com/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:948381,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

<div class="container">
<h1>New Article</h1>

<%= render 'form', article: @article %>
</div>

app/views/articles/search.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120935558-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120935558-1');
</script>

<!-- Hotjar Tracking Code for http://uglymalaysia.vz2k7vdg9a.ap-southeast-1.elasticbeanstalk.com/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:948381,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

<h1> hello </h1>
<% @article.each do |x| %>
  <p> Title: <%= x.title %> </p><br>
  <p> Description:<%= x.description %></p><br>
<% end %>

app/views/articles/show.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120935558-1"></script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120935558-1');
</script>

<!-- hotjar installed -->
<script>
  (function(h,o,t,j,a,r){
    h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
    h._hjSettings={hjid:948381,hjsv:6};
    a=o.getElementsByTagName('head')[0];
    r=o.createElement('script');r.async=1;
    r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
    a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<!-- hotjar end -->

<div class="wrapper">
  <header class="main-head">
  <!-- Header for images/title together -->
    <div class="header mt-5">
      <% if @article.videos.length != 0 && @article.images.length != 0 %>
        <!-- Show video and image together in carousel -->
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @article.videos.each do |video| %>
              <div class="carousel-item active center-item">
                <%= video_tag video.to_s, controls: true, size: "250"%>
              </div>
            <% end %>
            <% @article.images.each do |img|%>
              <div class="carousel-item center-item">
                <%= image_tag(img.large.url, size: "600x600") %>
              </div>
            <% end %>
          </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
        <!-- End of show video and image -->
      <% elsif @article.images.length!= 0 %>
        <!-- only for image carousel -->
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @article.images.each_with_index do |img, index|%>
              <% if index == 0 %>
                <div class="carousel-item active center-item">
                  <%= image_tag(img.large.url, size: "600x600") %>
                </div>
              <% else %>
                <div class="carousel-item center-item">
                  <%= image_tag(img.large.url, size: "600x600") %>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <hr>
    <div class="show-header">
      <p><%= @article.title  %></p>
    </div>
      </br>
    <div class="author">
      <p>Posted on <%= @article.created_at.strftime("%d %B %Y") %> |
        <%= @article.impressionist_count(:filter=>:ip_address) %> Views
      </p>


    </div>
  </header>


  <!-- Social share side -->
  <nav class="main-nav">
    <div class="sticky-social">
      <ul>
        <!-- AddToAny BEGIN -->
        <p>Share via:</p>
          <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
            <a class="a2a_button_facebook"></a>
            <a class="a2a_button_twitter"></a>
            <a class="a2a_button_google_gmail"></a>
            <a class="a2a_button_whatsapp"></a>
            <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
          </div>
        <!-- AddToAny END -->
      </ul>
    </div>
  </nav>
  <!-- Social Share End -->

  <!-- Article -->
    <article class="content">

      <!-- Article body -->
      <p><%= @article.description  %></p>

        <p>Number of views
          <%= @article.impressionist_count(:filter=>:ip_address) %>
        </p>

        <!-- If signed in, show this -->
      <% if current_user %>
        <% vote = Vote.find_by(article: @article.id, user_id: current_user.id) %>
        <!-- If no vote -->
          <% if !vote.nil? %> <!-- if vote find_by not nil is true-->
            <% if vote.vote? %>  <!-- if vote value is true-->
              <%= link_to "UPVOTE | #{Vote.where(article_id: @article.id, vote: true).count}", upvote_article_votes_path(@article), class: "btn btn-default btn-sm upvote", :remote => true %>
              <%= link_to "DOWNVOTE | #{Vote.where(article_id: @article.id, vote: false).count}", downvote_article_votes_path(@article), class: "btn btn-default btn-sm downvote", :remote => true %>
            <% else %>
              <%= link_to "UPVOTE | #{Vote.where(article_id: @article.id, vote: true).count}", upvote_article_votes_path(@article), class: "btn btn-outline-default btn-sm upvote", :remote => true %>
              <%= link_to "DOWNVOTE | #{Vote.where(article_id: @article.id, vote: false).count}", downvote_article_votes_path(@article), class: "btn btn-default btn-sm downvote" , :remote => true%>
            <% end %>
          <% else %>
            <%= link_to "UPVOTE | #{Vote.where(article_id: @article.id, vote: true).count}", upvote_article_votes_path(@article), class: "btn btn-outline-secondary btn-sm upvote", :remote => true %>
            <%= link_to "DOWNVOTE | #{Vote.where(article_id: @article.id, vote: false).count}", downvote_article_votes_path(@article), class: "btn btn-default btn-sm downvote" , :remote => true%>
          <% end %>
          <!-- If not sign in, show this -->
      <% else %>
        <%= link_to "UPVOTE | #{Vote.where(article_id: @article.id, vote: true).count}", upvote_article_votes_path(@article), class: "btn btn-outline-secondary btn-sm disabled", :remote => true %>
        <%= link_to "DOWNVOTE | #{Vote.where(article_id: @article.id, vote: false).count}", downvote_article_votes_path(@article), class: "btn btn-default btn-sm downvote disabled" , :remote => true%>
      <% end %>
    <% if current_user %>
      <% if current_user.id == @article.user_id%>
        <%= link_to 'Edit', edit_article_path(@article) %> |
        <%= link_to 'Back', articles_path %>
      <% else %>
        <%= link_to 'Back', articles_path %>
      <% end %>
    <% end %>


    </article>
    <!-- Article ends -->

<!-- Right side bar -->
<aside class="side">
  <div class="side-nav">
    <div class="header">
      <p class="title background">Pedas Stories</p>
    </div>
    <hr/ class="my-2">
    <% @articles.limit(5).each do |post|%>
    <!-- card deck -->
      <a href="<%= post.id %>">
        <div class="card shadow-sm">
          <div class="row">
            <div class="col-8 p-0">
              <div class="card-body d-flex flex-column">
                <div class="card-title"><%= post.title %></div>
                <div class="stats mt-auto">
                  <i class="fa fa-eye"></i> <%= post.impressionist_count(:filter=>:ip_address) %> <i class="fa fa-heart"></i> <%= Vote.where(article_id: @articles[0].id, vote: true).count %>
                </div>
              </div>
            </div>
            <div class="col-4 p-0">
              <div class="img-wrap">
                <% if post.images? %>
                <img class="card-img-right pull-right" src="<%= post.images[0].thumb if post.images? %>" alt="Card image cap">
                <% else %>
                  <img class="card-img-right pull-right" src="http://via.placeholder.com/85x85" alt="Card image cap">
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </a>
    <!-- card ends -->
    <% end %>
    <!-- deck end -->
    <div class="ad">
      <!-- advertisement card -->
      <div class="col-sm p-0 mt-3">
        <div class="card">
          <div class="card-body">
            <p class="card-text">Advertisement</p>
          </div>
        </div>
      </div>
      <!-- card end -->
    </div>
    <hr/ class="my-2">
    <ul class="footer-links d-flex flex-wrap justify-content-center">
      <li><%= link_to 'Advertise!', root_path, class: "" %></li>
      <li><%= link_to 'Help', root_path, class: "" %></li>
      <li><%= link_to 'Privacy', root_path, class: "" %></li>
      <li><%= link_to 'Terms', root_path, class: "" %></li>
      <li><%= link_to 'About', root_path, class: "" %></li>
      <li><%= link_to 'Contact', root_path, class: "" %></li>
    </ul>
  </div>
  <!-- side nav ends -->
<!-- sticky ends for right nav -->
</aside>

<% if @relevant_tag.length != 0 %>
  <footer class="main-footer">
    <p>Other stories like this</p>


    <div class="footer-wrapper">
      <%# byebug %>
        <% @relevant_tag.take(2).each do |relevant_article| %>
          <a href="<%= relevant_article.id %>">
            <div class="footer-box">
              <% if relevant_article.images == nil %>

              <% else %>
                <img class="footer-image" src="<%= relevant_article.images[0]%>" alt="Card image cap"  height="15" width="15">
              <% end %>


              <div class="footer-title">
                <%= relevant_article.title %>
              </div>

              <div class="footer-desc">
                <p>
                <%= relevant_article.description.first(40) %>
                ... read more<p>
              </div>
              <div class="stats mt-auto">
                <i class="fa fa-eye"></i> <%= relevant_article.impressionist_count(:filter=>:ip_address) %> <i class="fa fa-heart"></i> <%= Vote.where(article_id: @articles[0].id, vote: true).count %>
              </div>
            </div>
          </a>
       <% end %>

  </div>
<% end %>


 </footer>

 <div class="disqus" id="disqus_thread">
 </div>
 <script id="dsq-count-scr" src="//www-uglymalaysia.disqus.com/count.js" async></script>

</div>

<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
  this.page.url = "<%= request.original_url %>";
  this.page.identifier = 'article-<%= @article.id %>';

};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://uglymy-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript#disqus_thread">comments powered by Disqus.</a></noscript>

</body>

app/views/articles/tag_search.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120935558-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120935558-1');
</script>

<!-- Hotjar Tracking Code for http://uglymalaysia.vz2k7vdg9a.ap-southeast-1.elasticbeanstalk.com/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:948381,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

<% @article.each do |x| %>
  <p> Title: <%= x.title %> </p><br>
  <p> Description:<%= x.description %></p><br>
<% end %>