config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: "users/registrations" }

  get 'durian_runtuh', to: 'articles#most_views', as: :durian_runtuh
  get 'pedas', to: 'articles#trending', as: :pedas
  get 'latest', to: 'articles#latest', as: :latest
  get 'articles/search/:tag', to: 'articles#tag_search', as: :tag
  root 'articles#index'
  resources :articles do
  	resource :votes, only: [:upvote, :downvote] do
  		member do
  			get 'upvote'
        get 'downvote'
  		end
  	end
  end

  resources :devices, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device
  def new
    @device = Device.new
  end

  def create
     if @device.nil? || @device.created_at > 15.minutes.ago
       @device = Device.create(device_params)
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find_by(ip: remote_ip())
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.permit(:ip, :isp, :city, :state, :country, :postcode, :latitude, :longitude, :user_id)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: @device, url: devices_path, local: false, id: :device) do |f| %>

  <%= f.hidden_field :user_id, value: current_user %>
  <%= f.hidden_field :ip, id: "ip" %>
  <%= f.hidden_field :isp, id: "isp" %>
  <%= f.hidden_field :city, id: "city" %>
  <%= f.hidden_field :state, id: "state" %>
  <%= f.hidden_field :country, id: "country" %>
  <%= f.hidden_field :postcode, id: "postcode" %>
  <%= f.hidden_field :latitude, id: "latitude" %>
  <%= f.hidden_field :longitude, id: "longitude" %>

<% end %>